export const THEM_NGUOI_DUNG = "THEM_NGUOI_DUNG";
export const XOA_NGUOI_DUNG = "XOA_NGUOI_DUNG";
export const EDIT_NGUOI_DUNG = "EDIT_NGUOI_DUNG";
export const CAP_NHAT_NGUOI_DUNG = "CAP_NHAT_NGUOI_DUNG";
export const SEARCH_NGUOI_DUNG = "SEARCH_NGUOI_DUNG";
export const CAP_NHAT_NGUOI_DUNG_AVATAR = "CAP_NHAT_NGUOI_DUNG_AVATAR";
